In [133]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [134]:
dataset = pd.read_csv('diabetes.csv')

In [135]:
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [136]:
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [137]:
dataset.shape

(768, 9)

In [138]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [139]:
x = dataset[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']] 
y = dataset['Outcome']

In [140]:
from sklearn.model_selection import train_test_split

In [141]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = .30,random_state = 1)

In [142]:
from sklearn.linear_model import LogisticRegression 

In [143]:
reg = LogisticRegression()

In [144]:
reg.fit(xtrain,ytrain)

LogisticRegression()

In [145]:
reg.predict(xtest)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [146]:
reg.score(xtest,ytest)

0.7835497835497836

In [147]:
from sklearn.metrics import accuracy_score

In [148]:
predict = reg.predict(xtest)

In [149]:
accuracy_score(ytest,predict)

0.7835497835497836

In [150]:
reg.predict_proba(xtest)

array([[0.58040125, 0.41959875],
       [0.69594775, 0.30405225],
       [0.85395078, 0.14604922],
       [0.94499834, 0.05500166],
       [0.79048265, 0.20951735],
       [0.72197359, 0.27802641],
       [0.64280976, 0.35719024],
       [0.89586996, 0.10413004],
       [0.8349669 , 0.1650331 ],
       [0.78879965, 0.21120035],
       [0.56950872, 0.43049128],
       [0.92486097, 0.07513903],
       [0.01884576, 0.98115424],
       [0.27328751, 0.72671249],
       [0.97528377, 0.02471623],
       [0.28338009, 0.71661991],
       [0.76400335, 0.23599665],
       [0.69651883, 0.30348117],
       [0.87012086, 0.12987914],
       [0.84402774, 0.15597226],
       [0.61771926, 0.38228074],
       [0.86680808, 0.13319192],
       [0.04823581, 0.95176419],
       [0.73908752, 0.26091248],
       [0.92726303, 0.07273697],
       [0.59294036, 0.40705964],
       [0.79790815, 0.20209185],
       [0.27468522, 0.72531478],
       [0.91827874, 0.08172126],
       [0.54150109, 0.45849891],
       [0.

In [151]:
from sklearn.metrics import confusion_matrix

In [152]:
confusion_matrix(ytest,predict)

array([[132,  14],
       [ 36,  49]], dtype=int64)

In [153]:
from sklearn.metrics import classification_report

In [154]:
print(classification_report(ytest,predict))

              precision    recall  f1-score   support

           0       0.79      0.90      0.84       146
           1       0.78      0.58      0.66        85

    accuracy                           0.78       231
   macro avg       0.78      0.74      0.75       231
weighted avg       0.78      0.78      0.78       231



In [159]:
x1train,x1test,y1train,y1test = train_test_split(x,y,test_size = .25,random_state = 1)

In [160]:
reg.fit(x1train,y1train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [161]:
predict = reg.predict(x1test)

In [162]:
accuracy_score(y1test,predict)

0.7760416666666666

In [163]:
print(classification_report(y1test,predict))

              precision    recall  f1-score   support

           0       0.79      0.89      0.84       123
           1       0.74      0.58      0.65        69

    accuracy                           0.78       192
   macro avg       0.77      0.73      0.74       192
weighted avg       0.77      0.78      0.77       192



In [164]:
x2train,x2test,y2train,y2test = train_test_split(x,y,test_size = .40,random_state = 1)

In [165]:
reg.fit(x2train,y2train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [166]:
predict = reg.predict(x2test)

In [168]:
accuracy_score(y2test,predict)

0.75

In [169]:
print(classification_report(y2test,predict))

              precision    recall  f1-score   support

           0       0.77      0.87      0.82       199
           1       0.69      0.53      0.60       109

    accuracy                           0.75       308
   macro avg       0.73      0.70      0.71       308
weighted avg       0.74      0.75      0.74       308



In [170]:
x3train,x3test,y3train,y3test = train_test_split(x,y,test_size = .20,random_state = 1)

In [171]:
reg.fit(x3train,y3train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [172]:
predict = reg.predict(x3test)

In [173]:
accuracy_score(y3test,predict)

0.7792207792207793

In [174]:
print(classification_report(y3test,predict))

              precision    recall  f1-score   support

           0       0.79      0.90      0.84        99
           1       0.76      0.56      0.65        55

    accuracy                           0.78       154
   macro avg       0.77      0.73      0.74       154
weighted avg       0.78      0.78      0.77       154

